eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8001/eureka/
server:
  port: 8002
  servlet:
    context-path: /project
spring:
  redis:
    port: 6379
    host: 127.0.0.1
  application:
    name: project-user
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      url: jdbc:mysql://localhost:3306/project?characterEncoding=utf-8&useSSL=false
mybatis:
      configuration:
          map-underscore-to-camel-case: true
      mapper-locations: mybatis/**/*Mapper.xml