spring:
  application:
    name: project-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhouxiaoyang/testConfig.git
          username:
          password:
          basedir: E:\workfordemo\springCloudDemo\project-config\basedir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/